Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiPageAppApierce.Models;

namespace MultiPageAppApierce.Controllers
{
    public class FavoritesController : Controller
    {

        private CountryContext context;
        public FavoritesController(CountryContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Route("/Views/Favorites/Index.cshtml")]
        public ViewResult Index()
        {
            var session = new CountrySession(HttpContext.Session);
            var model = new CountriesViewModel
            {
                ActiveCategory = session.GetActiveCateg(),
                ActiveGame = session.GetActiveGame(),
                Countries = session.GetMyCountries(),
                UserName = session.GetName()
            };

            return View(model);
        }

        [HttpPost]
        public RedirectToActionResult Add(Country country)
        {
            country = context.Countries
                .Include(t => t.Category)
                .Include(t => t.Game)
                .Where(t => t.CountryId == country.CountryId)
                .FirstOrDefault() ?? new Country();

            var session = new CountrySession(HttpContext.Session);
            var cookies = new CountryCookies(Response.Cookies);

            var countries = session.GetMyCountries();
            countries.Add(country);
            session.SetMyCountries(countries);
            cookies.SetMyCountryIds(countries);

            TempData["message"] = $"{country.Name} added to your favorites";

            return RedirectToAction("Index", "Country",
                new
                {
                    ActiveCategory = session.GetActiveCateg(),
                    ActiveGame = session.GetActiveGame(),
                });
        }

        [HttpPost]
        public RedirectToActionResult Delete()
        {
            var session = new CountrySession(HttpContext.Session);
            var cookies = new CountryCookies(Response.Cookies);

            session.RemoveMyCountries();
            cookies.RemoveMyCountryIds();

            TempData["message"] = "Favorite teams cleared";

            return RedirectToAction("Index", "Home",
                new
                {
                    ActiveCategory = session.GetActiveCateg(),
                    ActiveGame = session.GetActiveGame(),
                });

        }
    }
}

Controllers/NameController.cs
using Microsoft.AspNetCore.Mvc;
using MultiPageAppApierce.Models;

namespace MultiPageAppApierce.Controllers
{
    public class NameController : Controller
    {
        public IActionResult Index()
        {
            var session = new CountrySession(HttpContext.Session);
            var model = new CountriesViewModel
            {
                ActiveCategory = session.GetActiveCateg(),
                ActiveGame = session.GetActiveGame(),
                Countries = session.GetMyCountries(),
                UserName = session.GetName()
            };

            return View();
        }

        [HttpPost]
        public RedirectToActionResult Change(CountriesViewModel model)
        {
            var session = new CountrySession(HttpContext.Session);
            session.SetName(model.UserName);

            return RedirectToAction("Index", "Country",
                new
                {
                    ActiveCategory = session.GetActiveCateg(),
                    ActiveGame = session.GetActiveGame()
                });
        }
    }
}

Views/Favorites/Index.cshtml
@model CountriesViewModel
@{
    ViewData["Title"] = "Favorites";
}

<div class="text-center">
    <h2>@(String.IsNullOrEmpty(Model.UserName) ? "My" : Model.UserName + "'s") Favorites</h2>
    <form asp-action="Delete" method="post">
        <a asp-action="Index" asp-controller="Country" class="btn btn-primary"
           asp-route-activeCategory="@Model.ActiveCategory"
           asp-route-activeGame="@Model.ActiveGame">
            Back to Home Page
        </a>
        <a asp-action="Index" asp-controller="Name" class="btn btn-primary">Change Name</a>
        <button type="submit" class="btn btn-primary">
            Clear Favorites
        </button>
    </form>
    <br />
</div>

<div class="row">
    <div class="col-8 offset-2">
        <ul class="list-group">
            @foreach (Country country in Model.Countries)
            {
                <li class="list-group-item">
                    <div class="col-sm-4">
                        <img src="~/images/@country.CountryFlag" alt="" />
                    </div>
                    <div class="col-sm-4">
                        @country.Name
                    </div>
                    <div class="col-sm-4">
                        @country.Category.CategoryName @country.Game.GameName
                    </div>
                </li>
            }
        </ul>
    </div>
</div>